version: "3"

services:
  db:
    container_name: didchat_db
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: didchat
      POSTGRES_PASSWORD: didchat
    ports:
      - 5433:5432
    volumes:
      - didchat-db-data:/var/lib/postgresql/data
    networks:
      - didchat_net
    restart: on-failure

  # mediator:
  #   container_name: didchat_mediator
  #   build:
  #     context: .
  #     args:
  #       PRISMA_DATABASE_URL: "postgresql://didchat:didchat@db:5433/prisma?schema=public"
  #   depends_on:
  #     - db
  #     - minio
  #   ports:
  #     - 9092:9092
  #   environment:
  #     PORT: 9092
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 5433
  #     DATABASE_USER: didchat
  #     DATABASE_PASS: didchat
  #     DATABASE_NAME_TYPEORM: veramo
  #     KMS_SECRET: e6d3f8e46a8ccee0718423b736e6418c05e48660c72f7879c36a7d116c
  #     DID_ALIAS: mediator.didchat.app
  #   networks:
  #     - didchat_net
  #   restart: always

networks:
  didchat_net:
    name: didchat_net

volumes:
  didchat-db-data:
  didchat-minio-data:
