version: "3"

services:
  db:
    container_name: didchat_db
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_USER=didchat
      - POSTGRES_PASSWORD=didchat
    ports:
      - 5432:5432
    volumes:
      - didchat-db-data:/var/lib/postgresql/data
    networks:
      - didchat_net
    restart: on-failure

networks:
  didchat_net:
    name: didchat_net

volumes:
  didchat-db-data:
