version: "3"

services:
  db:
    container_name: didchat_db
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_USER=didchat
      - POSTGRES_PASSWORD=didchat
    ports:
      - 5432:5432
    volumes:
      - didchat-db-data:/var/lib/postgresql/data
    networks:
      - didchat_net
    restart: on-failure

  minio:
    container_name: didchat_minio
    image: quay.io/minio/minio:latest
    command: server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: didchat
      MINIO_ROOT_PASSWORD: didchat123 
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5 
    hostname: minio
    volumes:
      - didchat-minio-data:/data
    networks:
      - didchat_net

networks:
  didchat_net:
    name: didchat_net

volumes:
  didchat-db-data:
  didchat-minio-data:
